language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
  - pip install pytest pytest-cov
# command to run tests
script:
  - pytest --cove=./ 
  - py.test test_api.py
#after successful run
after_success:
  - coveralls
  - codeclimate-test-reporter
